ARG VERSION_DOTNET
ARG VERSION_SUFFIX_DOTNET

FROM mcr.microsoft.com/dotnet/aspnet:${VERSION_DOTNET}${VERSION_SUFFIX_DOTNET}
EXPOSE 80

WORKDIR /tmp

RUN apt-get update && apt-get install -y \
        unzip \
        curl

# # Install Remote debugger
# WORKDIR /vsdbg
# RUN apt-get update \
#   && apt-get install -y --no-install-recommends \
#   unzip \
#   && rm -rf /var/lib/apt/lists/* \
#   && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

# Delete Temp files
RUN rm -Rf ./*
RUN rm -rf /var/lib/apt/lists/*
RUN apt-get clean && apt --fix-broken install

WORKDIR /app