ARG VERSION_DOTNET
ARG VERSION_SUFFIX_DOTNET

FROM mcr.microsoft.com/dotnet/sdk:${VERSION_DOTNET}${VERSION_SUFFIX_DOTNET}
ARG VERSION_NODEJS

# # Install Remote debugger
# WORKDIR /vsdbg
# RUN apt-get update \
#   && apt-get install -y --no-install-recommends \
#   unzip \
#   && rm -rf /var/lib/apt/lists/* \
#   && curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

# jre wont install unless man folder is created ...
RUN mkdir -p /usr/share/man/man1
RUN apt-get update -y && apt-get install -y \
  default-jre

# install nodejs
RUN curl --silent --location https://deb.nodesource.com/setup_${VERSION_NODEJS} | bash -
RUN apt-get install -y \
    nodejs

RUN npm i -g yarn pnpm

RUN  useradd --shell /bin/bash -u 1000 -o -c "" -m node
USER 1000

WORKDIR /src
VOLUME /src