name: Publish Node Package

on:
  push:
    branches:
      - "release/*"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Check Version
        run: |
          echo ${{github.ref}}
          echo ${{github.base_ref}}