name: Test context vars


on:
  pull_request:
    types: [closed]
    branches:
      - 'release/*'

jobs:
  setup:
    if: ${{ github.ref == github.base_ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - id: checkVersion
        name: Check Version
        uses: cpdevtools/action-versions@v0.5

      - name: Check Version
        run: |
          echo ${{github.ref}}
          echo ${{github.base_ref}}
          echo ${{github.head_ref}}